name: Build and Test

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run unit-tests

    - name: Build VSIX file
      run: npm run vscode:package
      
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mx-ide-vscode
        path: |
          *.vsix
        if-no-files-found: error
